VTP-118: add http method put
bdt-group/hapi pull request #6
Opened 2023-04-03 15:07 UTC by RomanKok

2023-04-03 15:11 UTC, Abel-ze-Normand commented
ещё нужно в hapi_json добавить подобное же API

2023-04-03 15:12 UTC, Abel-ze-Normand requested changes

2023-04-03 15:12 UTC, Abel-ze-Normand commented on src/hapi.erl
> +               {put, Body} -> Req0#{method => put, body => Body};
давай тут лучше просто сделаем матч {HTTPMethod, Body}, чтоб два одинаковых клоза не писать

2023-04-03 15:12 UTC, RomanKok commented on src/hapi.erl
> +               {put, Body} -> Req0#{method => put, body => Body};
ok

2023-04-04 08:12 UTC, Abel-ze-Normand approved these changes
LGTM

2023-04-04 08:16 UTC, merged